language: python
python:
 - "3.6"
install:
 pip install -r requirements.txt
job:
 include:
  -stage: Test
   script: python emp.py
           python test_emp.py
  -stage: Deploy
   script: python deploy.py

